---
  - ansible.posix.sysctl:
      name: vm.swappiness
      value: '0'
      state: present

  - ansible.posix.sysctl:
      name: net.bridge.bridge-nf-call-ip6tables
      value: '1'
      state: present

  - ansible.posix.sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: '1'
      state: present

  - ansible.posix.sysctl:
      name: net.ipv4.ip_forward
      value: '1'
      state: present
