# tasks file for master_configuration
---
  - name: Including required variables.
    include_vars:
      file: /root/k8s_multi_master_deployment/roles/node_preparation/vars/hosts_var.yaml 

  - name: Ensuring That docker is running.
    ansible.builtin.service:
      name: docker
      state: started

  - name: Initialized the master node in the cluster.
    ansible.builtin.shell: kubeadm init --control-plane-endpoint "{{ lb_hostname }}:6443" --upload-certs > /root/init_result.txt
    register: master_init_result
  - debug:
      msg: "{{ master_init_result }}"

  - name: Manipulating init_result.txt file to get the master joining command.
    ansible.builtin.shell: tail -n 12 /root/init_result.txt | head -3 > /root/master_join_command

  - name: Fetch the "master_join_command" file from initial master to admin node.
    ansible.builtin.fetch:
      src: /root/master_join_command
      dest: /root/
      flat: yes

  - name: Manipulating init_result.txt file to get the worker node joining command.
    ansible.builtin.shell: tail -n 2 /root/init_result.txt > /root/worker_join_command

  - name: Fetch the "worker_join_command" file from initial master to admin node.
    ansible.builtin.fetch:
      src: /root/worker_join_command
      dest: /root/
      flat: yes

  - name: Create the .kube directory inside the users home directory.
    file:
      path: $HOME/.kube
      state: directory
      mode: '0755'

  - name: Copying the /etc/kubernetes/admin.conf to $HOME/.kube/config.
    ansible.builtin.copy:
      src: /etc/kubernetes/admin.conf
      dest: $HOME/.kube/config
      remote_src: yes
      owner: root
      group: root

  - name: Checking the cluster initialization.
    ansible.builtin.shell: kubectl get nodes -o wide
    register: get_nodes_output
  - debug:
      var: get_nodes_output.stdout_lines

  - name: Download the "CALICO" manifest file.
    get_url:
      url: https://projectcalico.docs.tigera.io/manifests/calico-typha.yaml
      dest: /root/calico.yaml
         
  - name: Install "CALICO" for pod networking.
    ansible.builtin.shell: kubectl apply -f /root/calico.yaml

        
        #  - name: Getting the token for worker node joining.
        #    ansible.builtin.shell: kubeadm token create  --print-join-command
        #    register: generated_token_for_worker_node_joining
        #  - debug:
        #      msg : "{{ generated_token_for_worker_node_joining.stdout }}"
        #
        #  - name: Copy the joining command to a local file.
        #    local_action: copy content="{{ generated_token_for_worker_node_joining.stdout_lines[0] }}" dest="/root/kubernetes_join_command" mode=0777

      
